### ISSUE TITLE
 TypeError: prettyHtml is not a function

### ISSUE THREAD

**Issue by ralfr** [amelki/json-pretty-html#3]
Using the example you've provided I get a `TypeError: prettyHtml is not a function`. Any idea?

**Comment by rmchale** [comment]
I also get this error

**Comment by rmchale** [comment]
This seems to work:

```
var prettyHtml = require('json-pretty-html').default;
```

**Comment by amelki** [comment]
Thanks @rmchale, I must have introduced this when switching my build to Babel 6. 
I updated the README.
